[project]
name = "py-site-w-md-files"
version = "0.1.0"
description = "simple website from folders of markdown files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "jinja2>=3.1.5",
    "markdown>=3.7",
]
